- examples/js/selection/demo.js
- examples/js/selection/row-click-table.js
- src/BootstrapTable.js
- src/TableBody.js
- src/TableRow.js
#118 , I move the definition of onRowClick to options and add a exmples
> RE: [WIP] onRowClick feature

- src/BootstrapTable.js
- src/TableBody.js
- src/TableRow.js
Just to show you what I did to get the feature working. Simple but it works.
> [WIP] onRowClick feature

- src/TableRow.js
> fixed onrowclick bug

- src/BootstrapTable.js
- need to ignore hidden columns (what's shown is what's printed out)
- ignore pagination
> Bug (csv export) - bug on csv export

- examples/js/pagination/pagination-hook-table.js
- src/BootstrapTable.js
- src/store/TableDataStore.js
> Fix Missing multiColumnSearch if data reload

- README.md
- examples/js/column/column-width-table.js
- src/TableBody.js
- src/TableColumn.js
- src/TableHeaderColumn.js
> Fix sizing bugs in 1.2.11 tested in firefox

- src/BootstrapTable.js
- src/TableHeader.js
This is pretty self-explanatory.
> Add indeterminate status to select all checkbox

- css/react-bootstrap-table.css
- src/pagination/PaginationList.js
- src/toolbar/ToolBar.js
Sorry this took so long but I made my style improvements not depend on react-bootstrap, you can review and merge if you want.
> Make style improvements

- examples/index.html
- package.json
- src/pagination/PaginationList.js
- webpack.production.config.js
Reverts AllenFang/react-bootstrap-table#232
> Revert "Fix #197"

- gulpfile.js
- webpack.production.min.config.js
This adds another webpack configuration for an unminified production build. This PR supersedes #273.
> Add unminified build

- src/TableColumn.js
> Verify if props is null

- examples/js/column-filter/demo.js
- examples/js/column-filter/float-filter.js
it was initially unclear to me how to get floats to behave properly with sort + filter, so hopefully this helps someone
> example on how to use floats in grid

- examples/js/others/demo.js
- examples/js/others/expose-api-table.js
- src/BootstrapTable.js
Hi @AllenFang, thanks for your guided !!
This is about #353 I added the example page call expose-api-table, but the name and file path made me confusing.. I don't know that suitable ?
> Page by rowkey

- examples/js/manipulation/debounce-search-table.js
- examples/js/manipulation/demo.js
- src/BootstrapTable.js
- src/toolbar/ToolBar.js
Hi, @AllenFang this is my solution,
The search delay time feature solution for #330 #349.
use the `options` set `searchDelayTime`(type integer) in it, and it can helpful for set search delay.
it work well with my example.
> Search delay feature

- src/BootstrapTable.js
> improved the selectAll method with null data

- examples/js/manipulation/debounce-search-table.js
- src/toolbar/ToolBar.js
fixed the delay search table bug, it not real to wait for typing nothing before, and I fixed it this PR.
> urgent to fixed the delay search bug.

- examples/js/app.js
- examples/js/components/App.js
- examples/js/remote/demo.js
- examples/js/remote/remote-all.js
- examples/js/remote/remote-delete-row.js
- examples/js/remote/remote-export-csv.js
- examples/js/remote/remote-filtering.js
- examples/js/remote/remote-insert-row.js
- examples/js/remote/remote-paging.js
- examples/js/remote/remote-search.js
- examples/js/remote/remote-sorting.js
- examples/js/remote/remote-store-all.js
- examples/js/remote/remote-store-delete-row.js
- examples/js/remote/remote-store-export-csv.js
- examples/js/remote/remote-store-filtering.js
- examples/js/remote/remote-store-insert-row.js
- examples/js/remote/remote-store-paging.js
- examples/js/remote/remote-store-search.js
- examples/js/remote/remote-store-sorting.js
- src/BootstrapTable.js
- src/csv_export_util.js
- src/store/TableDataStore.js
It supports the following features in an external source of data:
- filtering
- searching
- sorting
- pagination
- adding a row
- deleting a row
- exporting to CSV
> With this PR, the BootstrapTable can now support remote data.

- src/store/TableDataStore.js
Columns with some null values are not sorted correctly.
> Fix sorting for null values

- example.html
Small change. Found it in the source. Worth surfacing for others!
> Add disabling radio/checkbox column to docs

- webpack.example.config.js
Hi, @AllenFang I always got this weird warning below, so I modified the webpack to resolve it, now it work find for me, thanks for check it ~
> fixed-webpack

- examples/js/selection/all-select.js
- examples/js/selection/demo.js
An example to solve #537 issue
> add a select-all (with filter and pagination) example

- src/BootstrapTable.js
fixed #578 issue,
Intent BootstrapsTable allow string and number.
> Fixed #578

- src/csv_export_util.js
> disable BOM on exported CSV file

- src/toolbar/ToolBar.js
> hide "Export to CSV" button when printing

- src/BootstrapTable.js
> use return value from onCellEdit as new cell value

- src/BootstrapTable.js
Updated to use sizePerPage from remote component when remote = true.
> Pagination fix sizePerPage for issue #659

- examples/js/advance/validator-table.js
- src/TableEditColumn.js
- src/toolbar/ToolBar.js
Just added the possibility to set own notification title and message after validation response.
> Customized for notification messages after validation  

- src/pagination/PageButton.js
> Added bootstrapv4 classes to pagination

- src/toolbar/InsertModal.js
- src/toolbar/ToolBar.js
- webpack.example.config.js
Hi @AllenFang, I try to added plugin to show the webpack building progress.
1. Add plugin to show webpack building progress.
2. fixed some eslint rule.
> added progress for webpack and modified eslint correct rule

- src/filters/Select.js
Add selectText as a prop to filter prop.
An example:
<TableHeaderColumn ref='nameCol' dataField='quality' filterFormatted dataFormat={ enumFormatter }
formatExtraData={ qualityType } filter={ { type: 'SelectFilter', options: qualityType, selectText: 'Choose' } }>Product Quality</TableHeaderColumn>
> Add an option to customize the "Select" text on SelectFilter filter.

- src/TableRow.js
Not sure this works for every case, but it definitely fixes mine.
> Fixes #912

- src/util.js
I accidentally deleted the repo of PR #923 sorry.
> Allow percentage values in column width. Fixes #910

- examples/js/custom/pagination/fully-custom-size-per-page.js
fixed key warning from example
> fixed key warning

- src/TableBody.js
- src/TableEditColumn.js
Features for #876, try /examples/cell-edit 👍
> feature - use tab to change edit row

- css/react-bootstrap-table.css
- examples/js/expandRow/demo.js
- examples/js/expandRow/expand-row-by-column.js
- examples/js/expandRow/expand-row-with-selection.js
- examples/js/expandRow/expandRow.js
- src/BootstrapTable.js
- src/TableBody.js
- src/TableHeader.js
- src/util.js
> enhance expand row - added indication about expanded rows

- src/TableHeader.js
Fixes issue: https://github.com/AllenFang/react-bootstrap-table/issues/1122
> Fix hideSelectColumn not working in table header

- README.md
> Minor Update

- src/BootstrapTable.js
resolve #1256 
Iv'e only changed the src so it can all be compiled later upon release.
LMK if there is anything else [=
> Enable custom sort (issue #1256)

- src/BootstrapTable.js
- src/TableBody.js
- src/TableHeader.js
> Allow conditionally specify columns

- src/pagination/PaginationList.js
- src/pagination/SizePerPageDropDown.js
https://github.com/AllenFang/react-bootstrap-table/issues/1130
> issue-1130: added show to make size dropdown compatible with bootstrap4

- examples/js/selection/row-click-table.js
- src/BootstrapTable.js
Click events now track the column index in addition to the row, plus a minor correction to terminology.
> Track column index on click events

- src/BootstrapTable.js
- src/TableBody.js
- src/filters/Date.js
- src/filters/Number.js
- src/filters/Select.js
- src/pagination/PaginationList.js
- src/toolbar/ToolBar.js
[from this article](https://medium.freecodecamp.com/functional-setstate-is-the-future-of-react-374f30401b6b), maybe it can be helpful in the future.
> use functional insteads object for setState

- src/BootstrapTable.js
int componentWillReceiveProps functions
Add checking code
if (nextProps.data === undefined) {
return;
}
Before 
this.store.setData(nextProps.data.slice());
> Fixed one small issue for BootstrapTable.js

- webpack.umd.min.config.js
This will reduce output file size and also prevent __REACT_HOT_LOADER__ related stuff getting added to minified file.
File size:
Original: **~251KB**
After change: **~226KB**
> setting environment to production

- examples/js/remote/remote-store-all.js
> Changed class name

- src/pagination/PaginationList.js
Exported totalPages property to custom pagination panel as we want to show total number of pages in my custom pagination panel.
> exported totalpages to custom pagination panel

- src/TableHeaderColumn.js
> Fix filter undefined
