src/BootstrapTable.js
src/TableBody.js
src/TableFilter.js
src/store/TableDataStore.js

Needed to be able to save checked item list further up so that it could be passed in again if the component was unmounted and then remounted (via react-router in this case). Simple changes just to allow 'selected' array as a prop.
The super call changes were just due to babel yelling at me that you cannot access 'this' before a super call. You can safely ignore them if this was just oddities in my transpiling process.
Also, on an unrelated note, setting props to true with prop={true} is unnecessary. It can certainly be clearer, but I think this looks a bit cleaner:
```js
<BootstrapTable data={products} striped hover pagination search>...
```
Anyhow, thanks for the great work on this.

Added 'selected' as a prop to allow setting selected state externally

---

dist/react-bootstrap-table.min.js
lib/TableBody.js
src/TableBody.js

Currently, when tables have no data, or a search returns no data the table looks a little odd and empty. This PR adds the below behaviour instead of rendering the table with no rows.

Show a message when the table is empty

---

lib/index.js

Node.Js will throw an error if you check for "window" directly. This is a workaround for that problem.

Fix "window is undefined" bug on node.js

---

src/csv_export_util.js

@AllenFang excel default open is by comma delimited so it's annoying to open manually with tab delimited.
So I changed it back to comma delimiter with "" wrapped around to escape the commas in cell.

Chore: csv back to comma delimited

---

src/index.js

Example use
var ReactBsTable = window.BootstrapTable;
var ReactTds = window.TableDataSet; //import TableDataSet
var dataSet = new ReactTds(products);

TableDataSet is now available via Window object

---

src/pagination/PaginationList.js

It broke the pagination buttons.

Don't hide pagination size selector column when there isn't a pagination dropdown

---

src/toolbar/ToolBar.js

On an iPhone sized screen, the search box becomes one and a half characters wide. It also overlaps on top of some buttons if they are enabled.
This further doesn't make sense if none of the three buttons in the first column (exportCSV, deleteBtn, insertBtn) are even enabled.
My change ensures the search field sits below the buttons and at a decent width for small screens.
The change which prompted this issue was [this one](https://github.com/AllenFang/react-bootstrap-table/commit/8e43d26d03cb378bfd7f70e57b495248c134730e#diff-c2216bf93dd49b5ad9bf3f7422d40ffcR144).
By the way, I'm loving this library, it's fantastic! Awesome job everyone!

Search bar too small on small screens (eg. iphone4/5)

---

package.json
src/Notification.js

It does not run without that. 
```
Uncaught TypeError: Cannot read property 'ToastContainer' of undefined: Notification.js:31
```
Just did: 
```
npm install 
gulp example-server
```

Fixed issue with ToastContainer.

---

advance.html
contributor.html
docs.html
example.html
index.html
start.html

Some of the assets on the docs branch aren't being rendered (certainly in Chrome, probably in other browsers) as they're being served over `http` rather `https`, which breaks some of the examples.

Fix doc assets being incorrectly served over http

---

src/store/TableDataStore.js

When the table column are hidden/rendered programmatically(depending on state), the `this.colInfos[sortField]` returns undefined.
Check if the column exist before the column is sorted.

Fix: The table should be sortable when a column is hidden programmatically

---

src/BootstrapTable.js

I've changed the order of preference for page and pagination size when receiving props. It would prefer nextProps over current page, which caused problems for me. It might work when you handle the selection inside the component, but as I'm giving this as a prop, it's triggered at times when it wasn't expected.
With this PR it'll prefer current page and pagination size over the ones provided by props.

Fix pagination lost bug

---

src/TableHeaderColumn.js

Some people can not notice that they can sort the table column by clicking the header cell or which column is sortable when they simply see the sortable table at first.
I suggest to show default caret on sortable column to enhance the value of this awesome library.
Thanks

Show default caret to tell user which column is sortable

---

examples/js/pagination/custom-pagination-table.js
src/BootstrapTable.js
src/pagination/PageButton.js
src/pagination/PaginationList.js

Hi, I made some changes and adjustments to the way in which the pagination of the tables works:
- If the table has only one page (or no pages at all), it won't show the navigation controls (first, prev, next, last).
```
[ 1 ]
```
- If the user is on the very first or the very last page of the table, it won't show the first/prev or next/last buttons respectively:
```
([ 1 ]) [ 2 ] [ 3 ] [ 4 ] [>] [>>]
[<<] [<] [ 7 ] [ 8 ] ([ 9 ])
```
- If the first or the last page is within the range of the pagination size, it won't show the first or last button respectively:
```
[<] [ 1 ] ([ 2 ]) [ 3 ] [ 4 ] [>] [>>]
[<<] [<] [ 7 ] ([ 8 ]) [ 9 ] [>]
```
(_These two last changes were made because in that way you can instantly show to the user where the table begins and ends._)
I also add some props on the …

Change pagination behavior and add more customization options to it

---

src/TableColumn.js

This PR is related to #260 
When we update state, TableColumn's shouldComponentUpdate throws an error, so the table is not updated correctly.
```js
if(typeof children === 'object') {
if(children.props.type === 'checkbox' || children.props.type === 'radio') {
```
`typeof` operator returns 'object' when it receives null value, so when we try to access to the props of `children`, a ReferenceError is thrown.

Fix null check bug

---

src/pagination/PaginationList.js

… provided.
When no sizePerPageList prop is supplied, or if there's only one element, the class on the pageList is now properly set to reduce instances of button overflow.

Pagination formatting fix

---

src/TableHeaderColumn.js

With small columns, it's not sure the full header text can fit.
To account for this case, set the title attribute of the column header to the text of the column header.
That way, if the text is not completely visible, hovering the mouse on the header will display the text.
This makes the assumption that this.props.children is a string, but that seems to be already the case for the filters seem to expect that.
Otherwise, it might be convenient to allow manually setting the title attribute as a property of TableHeaderColumn

Set the column text as the title of the column header

---

examples/js/selection/externally-managed-selection.js
src/BootstrapTable.js

improve the example about selection externally-managed-selection last page event issue, because the last page always back to the first page.
1. added the currPage state for externally-managed-selection to avoid if the state was changed, and get the correct page.
2. added the handleSelectRow result call back, currPage parameter.
I think changed this issue maybe improve the user experience.

improve the example about selection externally last page event issue

---

examples/js/sort/custom-sort-with-extra-data-table.js
examples/js/sort/demo.js
src/BootstrapTable.js
src/TableHeaderColumn.js
src/store/TableDataStore.js

The example shows how a column that displays enum values can be sorted according to those values and not the enum number.
const qualityType = {
0: 'good',
1: 'bad',
2: 'unknown'
};
Indeed, instead of sorting item tables according to the enum keys 0, 1 and 2 it is possible to sort now by the enum values "good", "bad" and "unknown" alphabetically which makes more sense since this is what the user can see.
ASC order will show "bad" items, then "good" items then "unknown" items (alphabetical order is respected), instead of showing "good", then "bad", then "unknown".

When using a custom sort function, pass any other extra data.

---

examples/js/advance/demo.js
examples/js/advance/validator-row-notifier-table.js
src/Editor.js
src/TableBody.js
src/TableEditColumn.js
src/toolbar/ToolBar.js

Hi, This is the fixed for #398 
BTW this time I added a little features for table row validator notifier, if you want to use the notifier for table text field, but must be use object like:
```javascript
function jobNameValidator(value) {
if (!value) {
return {
validate: false,
tip: 'Job Name is required!'
};
} else if (value.length < 10) {
return {
validate: false,
tip: 'Job Name length must great 10 char'
};
}
return true;
}
```
and the notifier work on table row.
or see the example /examples/js/advance/validator-row-notifier-table.js
I didn't fine other bug for it now, but maybe it will affect other features..

Fixed validator type

---

examples/js/complex/app.js
examples/js/pagination/custom-pagination-table.js
src/BootstrapTable.js
src/pagination/PaginationList.js

Hi, this is a proposal for a small improvement to the pagination feature
I've added an option (paginationShowsTotal) that if set to true will display a short text giving the current lines displayed + the total number of elements (for instance: showing rows 5 to 9 of 45)
This is convenient when using the pagination (since only react bootstrap table knows what is the current page) but also when used in conjunction with filtering (it tells you how many lines match the filter which again we can only access from within react bootstrap table)
Let me know what you think

Show position + total lines displayed

---

src/filters/Date.js
src/filters/Regex.js
src/filters/Text.js

When the component checks whether there is a default filter applied, it fetches the value from defaultValue.
This does not work. defaultValue on the input component is empty.
The value property however, contains the correct value.
Without this fix, the defaultValue property for the filter is not applied for text, regex and dates

Fix filter default value

---

.eslintrc
examples/js/pagination/custom-pagination-table.js
examples/js/remote/remote-paging.js
gulpfile.js
src/BootstrapTable.js
src/Const.js
src/pagination/PaginationList.js

I am using a service which uses 0-based indexing for paginating their API. I wanted a way in which I would simply map the state of my URL to params for their API. Rather than manually decrementing the `page` param each time I wanted to make an API, I think it would be cleaner, more robust, and simpler to maintain to simply allow for non-zero based indexing in react-bootstrap-table.
What this PR does is allow for the configuration option `pageStartIndex`. which allows the user to specify which page to begin paginating from.
If there is anything that needs to be changed, please let me know!
Cheers,
Ian

Add support for pagination start index

---

src/TableBody.js

The current implementation results is the following warning:
Warning: `NaN` is an invalid value for the `width` css style property. Check the render method of `TableBody`.

Don't set column width when it is null

---

src/store/TableDataStore.js

The fix for #427 (#428) is too aggressive in the sense that it prevents altogether to filter in a value of null.
Whatever the input in the filter input, it's impossible to include the line (it returns false systematically to the filter function on a null value)
I'd like to suggest a different fix. Instead of returning false, we set targetVal to the empty string in case the value is null or undefined. I believe this makes sense since the input from the user will be mostly text based (we could imagine custom filters for which it's not true) but in most cases it is. So assuming that having a value of null or undefined maps to an empty string seems sensible.
With that change, it becomes possible to filter in null values using the regex filter for instance and specifying a regex that only …

Fix for #506 impossible to filter in null values

---

src/toolbar/ToolBar.js

Hi, @AllenFang 
I added the esc (close) behavior in ToolBar react-modal, and I would not to mutate the origin "modal" variant by just use React.cloneElement, I think maybe it can be friendly for user to switch it.

improvement react-modal esc behavior

---

src/toolbar/ToolBar.js

The save button is not an *informational alert message* but rather ... *a successful or positive action*. This can confuse users.
See the [bootstrap documentation for the button classes](http://getbootstrap.com/css/#buttons-options):
```html
<button type="button" class="btn btn-success">Success</button>
<button type="button" class="btn btn-info">Info</button>
```

Use `btn-primary` for the Save button

---

examples/js/cell-edit/custom-cell-edit-table.js
examples/js/cell-edit/demo.js
src/BootstrapTable.js
src/TableBody.js
src/TableEditColumn.js

Addresses #162
- This isn't ready to merge by any means. I got something working so I could wrap my brain around the problem. Now I'm wondering what the best interface could be. I believe I have a change that may not be backwards compatible - fieldValue is now being passed from TableBody to TableEditColumn as an attribute.
- This is a working example:

Adding ability to provide custom editors

---

docs.html

BootstrapTable accepts "defaultSearch" option that's not mentioned in the docs

Add "defaultSearch" option in documentation

---

src/store/TableDataStore.js

This could generate thousands of console messages for large dataset. Proposing we just remove the console error. 
/cc @AllenFang

Remove console error for invalid regex

---

src/BootstrapTable.js

This might not be optimal. If you just want the table headers to be the same size as the columns, it is fine. If you need scroll bars on your table, then it won't work. The two are mutually exclusive.

Add an option to make the tables printer friendly. Fixes issue #430

---

src/store/TableDataStore.js

fixed #768, This is my solution to avoid filter misunderstand 0 become false.
```
<BootstrapTable data={ products } search={ true } options={ options }>
<TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
<TableHeaderColumn dataField='name' searchable={ false }>Fruit Name</TableHeaderColumn>
<TableHeaderColumn dataField='price' searchable={ false }>Product Price</TableHeaderColumn>
</BootstrapTable>
```
when id equals number 0 then filter can know it in this special case.

fixed #768 to filter number 0

---

src/BootstrapTable.js

Fixes onFilterChange Handler binding for dynamic generated columns (fixes #614)
(cleaned repo from #782)

Fixes handler binding for dynamic generated columns

---

src/BootstrapTable.js

Move to the last page only if the row is added at the end, otherwise, switch to the first page if pagination is enabled.
Fixes #808

Move to last page only if row is added at the end

---

package.json

add history dependency

---

src/BootstrapTable.js
src/store/TableDataStore.js

Throwing literals can mess up the stack trace and produce weird bugs. I forgot to add an unique key and [redbox](https://github.com/commissure/redbox-react) got messed up and was quite hard to find the actual error.
http://eslint.org/docs/rules/no-throw-literal
http://www.devthought.com/2011/12/22/a-string-is-not-an-error/

Throw errors instead of string literals

---

examples/js/expandRow/demo.js
examples/js/style/demo.js
examples/js/style/table-styled-components.js
package.json
src/BootstrapTable.js

[Styled components](https://github.com/styled-components/styled-components) is a package to style components with _CSS in JS_ concepts. 
As explained in their [docs](https://github.com/styled-components/styled-components#third-party-components),  the only requirement to use styled-components with third-party components is the following:
> Note: styled-components generate a real stylesheet with classes. The class names are then passed to the react component (including third party components) via the className prop. For the styles to be applied, third-party components must attach the passed-in className prop to a DOM node.
You only need to pass `this.props.Classname` to the wrapper div's className prop on `BoostrapTable.js`. 
```javascript
classSet('react-bs-table-container', …
```

Adding support for styled-components

---

src/store/TableDataStore.js

There was a bug in multi column sort where the orders and sort fields  would be reversed on table redraws without the user changing the sort info. This was because array.reverse() was used which changes the underlying array. Applying slice().reverse() first makes a copy of the original array and then returns the reverse of it, leaving the original arrays in a correct state.

Fixed sorting bug for multi column sort

---

src/TableHeaderColumn.js

These were set to Proptypes.Object which results in the propType being  'undefined' .

Fix propTypes for tdStyle and thStyle

---

src/TableBody.js

If table source data is built by immutable object list, e.g. by seamless-immutable or immutable-js library, the table will be broken if list is empty, which is caused by a push action to the list.

fix an exception if table source data is immutable type

---

css/react-bootstrap-table.css

This prevents the New button from being above the Insert Modal (the second issue referenced in #1145).

Increase modal z-index.

---

src/BootstrapTable.js

Changing the "expanding" option was not changing which rows were selected. Setting an initial list of expanded rows worked, but modifying that list through the props to BootstrapTable did not work.
The value being passed down to TableBody is `this.state.expanding`, but that is only set from props as part of the constructor, so changes to props.options.expanding of an already mounted BootstrapTable weren't being taken into account.
I've added some handling in componentWillReceiveProps to deal with change to `options.expanding`. I've copied the pattern used for the pagination options.

Fixing problem with externally controlling expanded rows.

---

.travis.yml
__tests__/BootstrapTable-test.js
__tests__/TableHeaderColumn-test.js
__tests__/store/TableDataStore-test.js
examples/js/manipulation/demo.js
examples/js/manipulation/strict-multi-search-table.js
examples/js/manipulation/strict-search-table.js
package.json
src/BootstrapTable.js
src/store/TableDataStore.js

Use Case: the user enters one search term and still sees too many entries: they just have to enter a second search term (separated by a whitespace) to narrow the filter further down.
----
The `multiColumnSearch` prop allows for multiple terms to be entered into a search field in order to display all rows that contain at least one of the given terms.
With the introduction of an additional `strictSearch` prop, we can achieve and AND search filter, i.e. only those rows are displayed that contain all of the search terms (in whatever order). In combination with the `multiColumnSearch` this allows for such an AND search filter over all `searchable` columns.
If unspecified, the `strictSearch` will be set to `!multiColumnSearch` to preserve the current default behaviour.

Conjunct Multi Column Search

---

src/filters/Select.js

The filter changed callback will be called less often, and in particular it will not be called when the options object has changed but has the same entries. This should fix issue #1187 
This is only a proposition, and other strategies are possible. In particular, I implemented the comparison function because the options object is always flat. It is also possible to use an external package like deep-equals or similar.

Fix callback condition in Select filter

---

css/react-bootstrap-table.css
examples/js/style/style.css

Issue #414 touches on how this library adds margins surrounding the table, which was addressed in e60e607ca8a01ec89cd728196f083636bd7f99bf by allowing a `style="..."` override. However, I don't feel this is the right approach to this specific issue.
Bootstrap tables don’t have any surrounding margins by default*. Therefore when using this library to create bootstrap tables, there shouldn’t be any surrounding margins by default, either.
This PR maintains the intended margins between components inside react-bootstrap-table (such as the toolbar or pagination area), while removing the margin surrounding the table.
\* Bootstrap tables do have a margin-bottom of 20px that their docs override, however I don’t think this PR is the right place to address that.
Original "complex" example:
"Complex" …

Maintain default bootstrap table margins

---

src/Editor.js

We can use only 4 types for editable type, `textarea`, `select`, `checkbox`, and `datetime`. and other types will be ignored.
doc: http://allenfang.github.io/react-bootstrap-table/docs.html#editable
This is because of this commit. [eslint on phase1](https://github.com/AllenFang/react-bootstrap-table/commit/e5310fa725f04c7d0290a4214326936c103512dc)
before: https://github.com/AllenFang/react-bootstrap-table/commit/e5310fa725f04c7d0290a4214326936c103512dc#diff-5b70bae4672cdf3d71d9f592ff139d08L78
```js
//process other input type. as password,url,email...
return(
<input {...attr} type={type} defaultValue={defaultValue}/>
)
```
after: https://github.com/AllenFang/react-bootstrap-table/commit/e5310fa725f04c7d0290a4214326936c103512dc#diff-5b70bae4672cdf3d71d9f592ff139d08R87
```js
// process other …
```

Fix Editor to use editable.type

---

examples/js/column-filter/all-filters.js
examples/js/column-filter/date-filter-programmatically.js
examples/js/column-filter/date-filter-with-default-value.js
examples/js/column-filter/date-filter.js
src/store/TableDataStore.js

When the DateFilter is used in conjunction with the builtin datetime field editor, TableDataStore.js throws an error. TableDataStore expects a Date, but the field editor (basically `<input type='datetime' />` returns a string. This needs to be checked for in TableDataStore.js, and the variable converted into a Date object if it's not already.
Along the same lines, the dateFormatter(cell, row) function in the examples also needs a similar check in order for both features (the date filter and date editor) to work together.

Fix bug when default DateFilter and date editor are used together

---

src/BootstrapTable.js

Faced with almost the same issue [#1161](https://github.com/AllenFang/react-bootstrap-table/issues/1161) when my header is grouped.
As far as I have understood here we assign row's width to header's width.
Why not just to iterate through real rows instead of children, because some children in this case are just groupped-headers?

fix #1116 - iterate through real children

---

src/BootstrapTable.js
src/csv_export_util.js

Hello guys! I have amounts in my table that uses comma to separate decimal digits, so when exporting my data into CSV  I got some problems since **onExportToCSV** function uses a comma by default. here is a PR that adds  a new prop in options named **exportCSVSeparator**, that's comma by default and can be overridden in BootstrapTable.
I tested It locally and it works fine.
Thank you.

custom CSV separator (unable to use semicolon instead)

---

src/TableEditColumn.js

I think it would be nice if there was an easy way to set attributes for editable inputs without having to create a customEditor. This allows stuff like:
```
editable={{type: 'number', attrs: {min: 1, max: 4, step: 1}}}
```
I'd only want it for simple attributes, but I don't like that it just silently ignores anything the user passes for ref, onKeyDown and onBlur and I'm not sure the best way to deal with it. Is it worth the extra code to support these, should ref and on* throw an error...?

Allow setting attributes on editable inputs

---

src/BootstrapTable.js

If I wrap TableHeaderColumn BootstrapTable read props only of wrapper, but don't read props of wrapped TableHeaderColum. This PR fix that behaviour.

Adding support of nesting TableHeaderColumn. Merge their props.

---

src/TableEditColumn.js

Pressing tab in an invalid editable field shows the validation error twice. Added a param to the validator function to disable notification in that case.

fix double validation error

---

src/filters/Select.js

IMO there is no need to check for defaultValue here. Just check for current selected value. Maybe this method can be removed, the state for isPlaceholderSelected is updated on every action in this class (f. e. filter, ...).
This fixes the github-issue #1568 - "placeholder-selected in filters/Select.js is not handled correctly" - (https://github.com/AllenFang/react-bootstrap-table/issues/1568)

Changed isPlaceholderSelected check in componentWillReceiveProps

---

src/BootstrapTable.js
src/TableHeaderColumn.js

Fixes #787 
**Problem:** dynamically changing the column set does not update the filters accordingly. As an example, if I'm filtering on column `A` and remove it from the column set, I'd like the internal data not to be filtered on `A` anymore.
**Solution:** the current implementation solves it in two steps:
1. `BootstrapTable.js` - internal filters: detect when a filtered column is removed, and clear column.
2. `TableHeaderColumn.js` - ui filters: detect when the `props.dataField` changes and update the underlying filter accordingly - explanations below.
Say you have a table with columns `A`, `B` and `C` with their underlying `TableHeaderColumn` instances `a`, `b` and `c` displaying them. If you remove column `B` and display only 2 columns, React will only use the first 2 component …

Fix filters on dynamic columns update

---

src/BootstrapTable.js
src/Const.js
src/store/TableDataStore.js

This is workaround for issue #1202. It adds a new FILTER_TYPE called `ArrayFilter` for filtering multiple values.
@AllenFang I know you have focus development on react-boostrap-table2, but I think this would be a small but useful improvement.
```
export default class ProgrammaticallyArrayFilter extends React.Component {
/* Filtering passing an array of values */
handleBtnClick = () => {
this.refs.table.handleFilterData({
name: { type: 'ArrayFilter', value: [ 'Item name 3', 'Item name 4' ] },
price: { type: 'ArrayFilter', value: [ 2100, 2104 ] }
});
}
render() {
return (
<div>
<button onClick={ this.handleBtnClick } className='btn btn-default'>Click to apply text filter</button>
<BootstrapTable ref='table' data={ products }>
<TableHeaderColumn dataField='id' isKey={ true }>Product …
```

Add new FILTER_TYPE 'ArrayFilter' to allow filtering on multiple values

---

src/BootstrapTable.js

Patch to solve this error : 
Uncaught TypeError: Cannot read property 'type' of undefined
at BootstrapTable.js:228
at forEachSingleChild (ReactChildren.js:49)
at traverseAllChildrenImpl (traverseAllChildren.js:75)
at traverseAllChildrenImpl (traverseAllChildren.js:91)
at traverseAllChildren (traverseAllChildren.js:170)
at Object.forEachChildren [as forEach] (ReactChildren.js:69)
at BootstrapTable.initTable (BootstrapTable.js:221)
at BootstrapTable.initTable (createPrototypeProxy.js:44)
at BootstrapTable.componentWillReceiveProps (BootstrapTable.js:419)
at BootstrapTable.componentWillReceiveProps (createPrototypeProxy.js:44)

Fix: Cannot read property 'type' of undefined

---

docs.html

Current on-line doc does not include any info about `fetchInfo` property, and it's very confused.

Add fetchInfo into doc

---

src/BootstrapTable.js
src/TableBody.js
src/TableColumn.js
src/TableRow.js

Close:
- https://github.com/AllenFang/react-bootstrap-table/issues/1774
- https://github.com/AllenFang/react-bootstrap-table/issues/1766

Add Event object to 'click' related events

---

css/react-bootstrap-table.css
examples/js/expandRow/custom-expand-indicator.js
src/BootstrapTable.js
src/ExpandRowHeaderColumn.js
src/TableHeader.js

I implemented new feature to expand/collapse all rows by using header column.
It can be shown/hidden based on "**showExpandAllHeaderColumn**", "**expandAllChilds**" properties configured as part of "**options**". Even we can define custom header column using "**expandedColumnHeaderComponent**" as part of "**expandColumnOptions**"

Added new feature Expand/Collapse All Rows by using Header Column

---

src/pagination/PaginationList.js

For the case where `prePage`, `nextPage`, `firstPage` and `lastPage` are custom elements, the pagination breaks because we're passing them as the `key` (which turns them into `[object Object]` and we end up with duplicate keys). A simple fix is to just use the page index as the key.
Fixes #1785 
Also, fix react proptype warnings for`prePage` (it shouldn't be a `string`) and add proptypes for the other

fix issue with key when using custom page elements

---

examples/js/pagination/demo.js
examples/js/pagination/icon-pagination-table.js
src/pagination/PageButton.js
src/pagination/PaginationList.js

Looks like custom page components are still not working as expected (my previous PR only fixed part of the issue, oops 😅). The problem now is that when you click on the `PageButton`, it calls:
```js
this.props.changePage(e.currentTarget.textContent);
```
It's expecting to get the page number from `e.currentTarget.textContent` which obviously won't work for custom components. Instead, I pass through the page number as a prop to the `PageButton`.
Also added a demo for further testing. I believe everything should work now!
Fixes #1785

fix bug with using custom pagination components

---

examples/js/basic/demo.js

Launched the demo locally as described here https://github.com/AllenFang/react-bootstrap-table, the current link led to 404 on github

Fixed link to scroll-table.js from the demo page
